
services:
  osbot_aws:
    build:
      context      : ../..
      dockerfile   : ./docker/lambda_python_nginx_supervisord/Dockerfile
    platform       : linux/amd64
    image          : diniscruz/lambda_python_nginx_supervisord
    container_name : lambda_python_nginx_supervisord
    ports          : ["9000:8080"]