services:
  osbot_aws:
    build:
      context     : ../..
      dockerfile  : ./docker/python_slim/Dockerfile
    image         : diniscruz/osbot_aws-python_slim
    container_name: osbot_aws_container

    env_file:
      - ../../.env