name: Run Python Integration Tests
description: 'Run Python Integration Tests'

inputs:
  package_name:
    description: 'Package name for coverage'
    required: true
  AWS_ACCESS_KEY_ID:
    description: 'AWS Account KEY ID'
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: 'AWS Secret Access Key'
    required: true
  AWS_DEFAULT_REGION:
    description: 'AWS Default region'
    required: true
  AWS_ACCOUNT_ID:
    description: 'AWS Account ID'
    required: true


runs:
    using: 'composite'
    steps:
      # API
      - name: Run pytest - Integration >>>> API
        shell: bash
        run: |
          coverage run --source=${{ inputs.package_name }} -m pytest -v -s --durations=0 tests/integration/api
        env:
          COVERAGE_FILE: .coverage.integration.api
          AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ inputs.AWS_DEFAULT_REGION    }}
          AWS_ACCOUNT_ID: ${{ inputs.AWS_ACCOUNT_ID        }}
          AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID     }}

      # _caches
      - name: Run pytest - Integration >>>> _caches
        shell: bash
        run: |
          coverage run --source=${{ inputs.package_name }} -m pytest -v -s --durations=0 tests/integration/_caches
        env:
          COVERAGE_FILE: .coverage.integration._caches
          AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ inputs.AWS_DEFAULT_REGION    }}
          AWS_ACCOUNT_ID: ${{ inputs.AWS_ACCOUNT_ID        }}
          AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID     }}

      # BEDROCK
      - name: Run pytest - Integration >>>> AWS | Boto3
        shell: bash
        run: |
          coverage run --source=${{ inputs.package_name }} -m pytest -v -s --durations=0 tests/integration/aws/bedrock
        env:
          COVERAGE_FILE: .coverage.integration.ecs
          AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ inputs.AWS_DEFAULT_REGION    }}
          AWS_ACCOUNT_ID: ${{ inputs.AWS_ACCOUNT_ID        }}
          AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID     }}

      # BOTO3
      - name: Run pytest - Integration >>>> AWS | Boto3
        shell: bash
        run: |
          coverage run --source=${{ inputs.package_name }} -m pytest -v -s --durations=0 tests/integration/aws/boto3
        env:
          COVERAGE_FILE: .coverage.integration.ecs
          AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ inputs.AWS_DEFAULT_REGION    }}
          AWS_ACCOUNT_ID: ${{ inputs.AWS_ACCOUNT_ID        }}
          AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID     }}

      # IAM
      - name: Run pytest - Integration >>>> AWS | IAM
        shell: bash
        run: |
          coverage run --source=${{ inputs.package_name }} -m pytest -v -s --durations=0 tests/integration/aws/iam
        env:
          COVERAGE_FILE        : .coverage.integration.ecs
          AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION   : ${{ inputs.AWS_DEFAULT_REGION    }}
          AWS_ACCOUNT_ID       : ${{ inputs.AWS_ACCOUNT_ID        }}
          AWS_ACCESS_KEY_ID    : ${{ inputs.AWS_ACCESS_KEY_ID     }}

      # Dynamo_db
      - name: Run pytest - Integration >>>> AWS | DYNAMO_DB
        shell: bash
        run: |
          coverage run --source=${{ inputs.package_name }} -m pytest -v -s --durations=0 tests/integration/aws/dynamo_db
        env:
          COVERAGE_FILE        : .coverage.integration.ecs
          AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION   : ${{ inputs.AWS_DEFAULT_REGION    }}
          AWS_ACCOUNT_ID       : ${{ inputs.AWS_ACCOUNT_ID        }}
          AWS_ACCESS_KEY_ID    : ${{ inputs.AWS_ACCESS_KEY_ID     }}


      # ECS
      - name: Run pytest - Integration >>>> AWS ECS
        shell: bash
        run: |
          coverage run --source=${{ inputs.package_name }} -m pytest -v -s --durations=0 tests/integration/aws/ecs
        env:
          COVERAGE_FILE        : .coverage.integration.ecs
          AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION   : ${{ inputs.AWS_DEFAULT_REGION    }}
          AWS_ACCOUNT_ID       : ${{ inputs.AWS_ACCOUNT_ID        }}
          AWS_ACCESS_KEY_ID    : ${{ inputs.AWS_ACCESS_KEY_ID     }}