name       : CD Pipeline - MAIN
on:
  push:
    branches:
      - dev


env:
  DOCKER__CONTEXT     : "."
  DOCKER_HUB__USERNAME: diniscruz
  DOCKER_HUB__TOKEN   : ${{ secrets.DOCKERHUB_TOKEN    }}
  GIT__BRANCH         : 'dev'
  PACKAGE_NAME        : 'osbot_aws'
  RELEASE_TYPE        : 'minor'

jobs:

  publish-to-pypi:
    permissions:
      id-token: write
    name: "Publish to PYPI"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Git Update Current Branch
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__update_branch@dev

      - name: publish-to-pypi
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/pypi__publish@dev
#    needs:
#      - increment-tag


  publish-to-docker-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Git Update Current Branch
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__update_branch@dev

      - name: Deploy to Docker Hub (latest)
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/docker-hub__publish@dev
        env:
          DOCKER__FILE: './docker/lambda_shell/Dockerfile'
          VERSION     : 'lambda_shell'
    needs:
      - publish-to-pypi
#      - name: Set $Version from file
#        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__read_version@dev

#      - name: Deploy to Docker Hub (current version)
#        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/docker-hub__publish@dev

#      - name: Deploy to Docker Hub (latest)
#        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/docker-hub__publish@dev
#        env:
#          VERSION: "latest"


#  publish-to-pypi:
#    permissions:
#      id-token: write
#    name: "Publish to PYPI"
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v4
#      with:
#        token: ${{ secrets.GIT_HUB__ACCESS_TOKEN }}
#        ref: dev
#
#    - name: publish-to-pypi
#      uses: ./.github/actions/publish-to-pypi
#    needs:
#      - increment-tag
#
