name       : CI Pipeline - DEV
on:
  push:
    branches:
      - dev

env:
  GIT__BRANCH  : 'dev'
  PACKAGE_NAME : 'osbot_aws'
  RELEASE_TYPE : 'minor'

jobs:

  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start Local Stack
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/docker__local-stack@dev
        with:
          LOCAL_STACK_SERVICES: 's3,lambda,iam,cloudwatch,dynamodb,logs,sts,ec2'

      - name: "run-tests"
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/pytest__run-tests@dev             # run tests (which use Local Stack)
        with:
          test_target: "tests"

  increment-tag:
    name: Increment Tag - DEV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Increment Tag (for DEV)
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__increment-tag@dev
        with:
          release_type: ${{env.RELEASE_TYPE}}
    needs:
      - run-unit-tests

  publish-to-pypi:
    #if: False
    permissions:
      id-token: write
    name: "Publish to PYPI"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Git Update Current Branch
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__update_branch@dev

      - name: publish-to-pypi
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/pypi__publish@dev
    needs:
      - increment-tag

